---
# Read the Docs configuration file for Sphinx projects

# Required
version: 2

# Set the OS and Python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation in the "docsrc/" directory with Sphinx
sphinx:
  configuration: docsrc/conf.py

# Zscaler doc build requirements
python:
  install:
    - requirements: docsrc/dev_requirements.txt
